### ISSUE TITLE
Peglin v0.7.53 Broken Mod Support

### ISSUE THREAD

**Issue by TreeofEmber** [ruiner189/Promethium#11]
I just wanted to let you know that all of your mods for Peglin seem to be not working in the new update v0.7.53
![Screenshot 2022-09-16 223400](https://user-images.githubusercontent.com/113752882/190842189-5823b930-e106-4b10-b8fd-b2bf28960648.jpg)

**Comment by ruiner189** [comment]
Thanks for letting me know! Been a bit busy, but I'm getting out the next set of updates out now.
