### ISSUE TITLE
Bug: Crash on Start

### ISSUE THREAD

**Issue by denny99** [ruiner189/Promethium#13]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1826849/206275191-862920f8-6957-4cc4-a941-9e5a4b137902.png">

I am getting this error message when starting peglin with your mod.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1826849/206275533-40d855bb-ec77-485e-8cbf-2fc0014822a5.png">

Also a lot of ingame placeholders seem to be broken. Might be related with the initial crash

Prometheum 1.4.1
ProLib 1.2.0
Peglin 0.8.10

**Comment by ruiner189** [comment]
The most recent of Peglin broke the mod (again). I'm currently uploading a new version right now! It should be available to play on Thunderstore in about 15-20 minutes. Once you update, please let me know if it works.

**Comment by denny99** [comment]
I cannot test it soon so assuming it will work :). I will reopen if it isn't fixed
