### ISSUE TITLE
[SUGGESTION] About the unicorn horn

### ISSUE THREAD

**Issue by MaxenceDC** [ruiner189/Promethium#2]
Make it so that the unicorn horn takes the electropegnet into account

btw, really great mod, thanks for your work!

**Comment by ruiner189** [comment]
That's going to be something a bit hard to change. If it was the old elctropegnet, then it would be more doable. I'll look into it, but can't promise any results

**Comment by MaxenceDC** [comment]
Thank you for your response, I'd be more than happy to see a feature like this one, or maybe it will be added in the vanilla game by the devs as a bug fix?

**Comment by ruiner189** [comment]
https://github.com/ruiner189/Promethium/releases/tag/1.2.0

I changed a lot on the prediction system. Please let me know how accurate it is now. There are still some cases where it's not accurate, but it should be much better than how it was
