### ISSUE TITLE
Odd German Orb and Armor Lock

### ISSUE THREAD

**Issue by Nicole-Evermore** [ruiner189/Promethium#3]
I found something called a Polus Test Orb, I think, and it's description was all in some kind of Germanic language. Dealt 22 Normal and Crit Damage and had something to do with causing confusion.
Same playthrough, I upgraded a stone to test the Armor effect, but the armor effect did not show on the upgrade, and on my next fight, I spawned in with armor, but the orbs did not load in and a Roman 2 was sitting in the middle of my screen, soft locking the run.

**Comment by ruiner189** [comment]
What version were you on, and do you have a player log?

Also were you playing on English or another language?

**Comment by Nicole-Evermore** [comment]
Set language was English. I was running version 1.0.9 of Promethium. It was the only mod active at the time. Using BepInEx x64 5.4.19.0. Sadly, I do not know where to find the Player Log as this is my first time modding Peglin.

Apologies for my delay in answering.

**Comment by ruiner189** [comment]
The player log can be found here: 

> %USERPROFILE%\AppData\LocalLow\Red Nexus Games Inc\Peglin\Player.log

And your save file is at 

> %USERPROFILE%\AppData\LocalLow\Red Nexus Games Inc\Peglin\Save_0.data

**Comment by Nicole-Evermore** [comment]
Ah, then I will reply again later when I arrive home with those files if I can find them.

**Comment by Nicole-Evermore** [comment]
I return, here are the documents you requested
[Player - Copy.txt](https://github.com/ruiner189/Promethium/files/8704057/Player.-.Copy.txt)
[Save_0 - Copy.txt](https://github.com/ruiner189/Promethium/files/8704058/Save_0.-.Copy.txt)
I had to change them to TXT files to get them to post here, sorry if that makes them unusable.

**Comment by ruiner189** [comment]
I should be home in about an hour. Those logs were very helpful!

**Comment by ruiner189** [comment]
https://github.com/ruiner189/Promethium/releases/tag/1.0.10

Please try this version and see if it works

**Comment by ruiner189** [comment]
I found the issue. The download for 1.0.9 was incorrect. Please let me know how this one works!

**Comment by Nicole-Evermore** [comment]
I will try your attached file when I get home this evening.

**Comment by Nicole-Evermore** [comment]
This seems to have worked! Thanks!
