### ISSUE TITLE
The Poker Chip stays the same as in vanilla.

### ISSUE THREAD

**Issue by Sambo3975** [ruiner189/Promethium#5]
The multipliers for the Poker Chip appear to remain the same when I have the mod installed. I have the latest version of Peglin and BepInEx and no other mods installed. The mod is loading, and all the other stuff in it seems to work fine.

**Comment by ruiner189** [comment]
What's the version of Promethium? It'll say on the main menu in the bottom right corner

**Comment by ruiner189** [comment]
Also there has been an update:
https://github.com/ruiner189/Promethium/releases/tag/1.0.10

**Comment by Sambo3975** [comment]
I did, indeed, just have an outdated version.
