### ISSUE TITLE
Restarting into a cursed run doesn't take away relics and orbs.

### ISSUE THREAD

**Issue by waterphoenix314** [ruiner189/Promethium#6]
![image](https://user-images.githubusercontent.com/22581126/168958617-a85e24a0-9ef0-4d0a-a5d2-1a3740944794.png)

**Comment by ruiner189** [comment]
What are your config settings, and are you using any other mods?

**Comment by waterphoenix314** [comment]
Everything should be default. As for mods, I had the gps mod in a previous run. For the pictured run I took it out and cleared my save beforehand.

**Comment by ruiner189** [comment]
Default behavior currently is keeping relics/orbs. You can change that in the config.

If you ever use custom start deck, I suggest removing it after loading in the relics/orbs you want as they have weird interactions when you start a new curse run.

**Comment by waterphoenix314** [comment]
Ah, my mistake I didn't look at the config file again after updating. There were only two options last time I checked in v1.0.9, if I remember correctly. Thanks for bringing my attention to the config, I love options.
