### ISSUE TITLE
Discard Health Damage Key

### ISSUE THREAD

**Issue by denny99** [ruiner189/Promethium#8]
Heyho,

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1826849/176911873-70f62c10-09ca-4434-b83f-bdb75f00303c.png">

You've changed the value of this key, but haven't changed it in the english translation.

Should I fix the translation? Or is this subject to change?

**Comment by ruiner189** [comment]
Sorry for the late reply.

What had happened is that I switch to the vanilla key (DISCARD_DAMAGE) instead of using my own key (DISCARD_HEALTH_DAMAGE) because they did the same thing (which that key got added from Orborous change) . Forgot to change it in the orbelisk! Thanks for pointing that out.
